# Prometheus Configuration for Trading Ecosystem Infrastructure
# Metrics collection for observability and monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trading-ecosystem'
    environment: 'development'

# Alertmanager configuration (to be added later)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Infrastructure services (via Prometheus exporters)
  - job_name: 'redis'
    static_configs:
      - targets: ['172.20.0.11:9121']  # Redis exporter
        labels:
          service: 'redis'
          service_type: 'infrastructure'
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['172.20.0.21:9187']  # PostgreSQL exporter
        labels:
          service: 'postgres'
          service_type: 'infrastructure'
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Service registry metrics endpoint
  - job_name: 'service-registry'
    static_configs:
      - targets: ['172.20.0.30:8080']
        labels:
          service: 'service-registry'
          service_type: 'infrastructure'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Audit Correlator - Singleton Service (TSE-0001.12.0)
  - job_name: 'audit-correlator'
    static_configs:
      - targets: ['172.20.0.80:8080']
        labels:
          service: 'audit-correlator'
          instance_name: 'audit-correlator'
          service_type: 'singleton'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Custodian Simulator - Singleton Service (TSE-0001.12.0)
  - job_name: 'custodian-simulator'
    static_configs:
      - targets: ['172.20.0.81:8080']
        labels:
          service: 'custodian-simulator'
          instance_name: 'custodian-simulator'
          service_type: 'singleton'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Exchange Simulator - Singleton Service (TSE-0001.12.0)
  - job_name: 'exchange-simulator'
    static_configs:
      - targets: ['172.20.0.82:8080']
        labels:
          service: 'exchange-simulator'
          instance_name: 'exchange-simulator'
          service_type: 'singleton'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Market Data Simulator - Singleton Service (TSE-0001.12.0)
  - job_name: 'market-data-simulator'
    static_configs:
      - targets: ['172.20.0.84:8080']
        labels:
          service: 'market-data-simulator'
          instance_name: 'market-data-simulator'
          service_type: 'singleton'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Risk Monitor - Singleton Python Service (TSE-0001.12.0)
  - job_name: 'risk-monitor'
    static_configs:
      - targets: ['172.20.0.85:8080']
        labels:
          service: 'risk-monitor'
          instance_name: 'risk-monitor'
          service_type: 'singleton'
          environment: 'docker'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Trading System Engine - Singleton Python Service (TSE-0001.12.0)
  - job_name: 'trading-system-engine'
    static_configs:
      - targets: ['172.20.0.86:8080']
        labels:
          service: 'trading-system-engine'
          instance_name: 'trading-system-engine'
          service_type: 'singleton'
          environment: 'docker'
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    scrape_timeout: 5s

  # Test Coordinator - Singleton Python Service (TSE-0001.12.0)
  - job_name: 'test-coordinator'
    static_configs:
      - targets: ['172.20.0.87:8080']
        labels:
          service: 'test-coordinator'
          instance_name: 'test-coordinator'
          service_type: 'singleton'
          environment: 'docker'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Future Go services (will be auto-discovered)
  - job_name: 'go-services'
    static_configs:
      - targets: []
    scrape_interval: 15s
    metrics_path: /metrics

  # Future Python services (will be auto-discovered)
  - job_name: 'python-services'
    static_configs:
      - targets: []
    scrape_interval: 15s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['172.20.0.50:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['172.20.0.60:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['172.20.0.70:8888']
    scrape_interval: 15s
    metrics_path: /metrics