# Grafana Datasource Configuration for Trading Ecosystem
# Automatically provisions Prometheus as primary datasource

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.20.0.40:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: false
      prometheusType: "Prometheus"
      prometheusVersion: "2.47.2"
      cacheLevel: "High"
      incrementalQuerying: true
      incrementalQueryOverlapWindow: "10m"
    secureJsonData: {}
    version: 1
    uid: "prometheus-trading-ecosystem"